### PR TITLE
Fix run-fuzzer.sh

### LINKED ISSUE #70: Failing to build libfuzzer-sys with sanitizers
Whenever I run ` ./run-fuzzer.sh`, I get a build failure compiling `libfuzzer-sys`:

```
 Compiling libfuzzer-sys v0.1.0 (https://github.com/rust-fuzz/libfuzzer-sys.git#bcaa8e1c)
error: failed to run custom build command for `libfuzzer-sys v0.1.0 (https://github.com/rust-fuzz/libfuzzer-sys.git#bcaa8e1c)`
process didn't exit successfully: `/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-b832cf5e294bfa00/build-script-build` (exit code: 1)
--- stderr
==17280==LeakSanitizer has encountered a fatal error.
==17280==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==17280==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
```

<details>
<summary> Full build log with LSAN_OPTIONS=verbosity=1:log_threads=1 </summary>

```
   Compiling libfuzzer-sys v0.1.0 (https://github.com/rust-fuzz/libfuzzer-sys.git#bcaa8e1c)
error: failed to run custom build command for `libfuzzer-sys v0.1.0 (https://github.com/rust-fuzz/libfuzzer-sys.git#bcaa8e1c)`
process didn't exit successfully: `/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-b832cf5e294bfa00/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerTraceState.o" "-c" "llvm/lib/Fuzzer/FuzzerTraceState.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilPosix.o" "-c" "llvm/lib/Fuzzer/FuzzerUtilPosix.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtil.o" "-c" "llvm/lib/Fuzzer/FuzzerUtil.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerCrossOver.o" "-c" "llvm/lib/Fuzzer/FuzzerCrossOver.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsDlsymWin.o" "-c" "llvm/lib/Fuzzer/FuzzerExtFunctionsDlsymWin.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilLinux.o" "-c" "llvm/lib/Fuzzer/FuzzerUtilLinux.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerShmemWindows.o" "-c" "llvm/lib/Fuzzer/FuzzerShmemWindows.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerShmemPosix.o" "-c" "llvm/lib/Fuzzer/FuzzerShmemPosix.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIO.o" "-c" "llvm/lib/Fuzzer/FuzzerIO.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMutate.o" "-c" "llvm/lib/Fuzzer/FuzzerMutate.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilDarwin.o" "-c" "llvm/lib/Fuzzer/FuzzerUtilDarwin.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIOWindows.o" "-c" "llvm/lib/Fuzzer/FuzzerIOWindows.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsWeakAlias.o" "-c" "llvm/lib/Fuzzer/FuzzerExtFunctionsWeakAlias.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIOPosix.o" "-c" "llvm/lib/Fuzzer/FuzzerIOPosix.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerLoop.o" "-c" "llvm/lib/Fuzzer/FuzzerLoop.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerDriver.o" "-c" "llvm/lib/Fuzzer/FuzzerDriver.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerSHA1.o" "-c" "llvm/lib/Fuzzer/FuzzerSHA1.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsWeak.o" "-c" "llvm/lib/Fuzzer/FuzzerExtFunctionsWeak.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsDlsym.o" "-c" "llvm/lib/Fuzzer/FuzzerExtFunctionsDlsym.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilWindows.o" "-c" "llvm/lib/Fuzzer/FuzzerUtilWindows.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMerge.o" "-c" "llvm/lib/Fuzzer/FuzzerMerge.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerTracePC.o" "-c" "llvm/lib/Fuzzer/FuzzerTracePC.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
PROFILE = Some("debug")
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c++11" "-fno-omit-frame-pointer" "-o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMain.o" "-c" "llvm/lib/Fuzzer/FuzzerMain.cpp"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/libfuzzer.a" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerTraceState.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilPosix.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtil.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerCrossOver.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsDlsymWin.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilLinux.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerShmemWindows.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerShmemPosix.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIO.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMutate.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilDarwin.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIOWindows.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsWeakAlias.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerIOPosix.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerLoop.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerDriver.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerSHA1.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsWeak.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerExtFunctionsDlsym.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerUtilWindows.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMerge.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerTracePC.o" "/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out/llvm/lib/Fuzzer/FuzzerMain.o"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
cargo:rustc-link-lib=static=fuzzer
cargo:rustc-link-search=native=/home/alan/workspace/fuzz/targets/target/debug/build/libfuzzer-sys-c0cf010c1a9d8732/out
TARGET = Some("x86_64-unknown-linux-gnu")
cargo:rustc-link-lib=stdc++

--- stderr
==17280==AddressSanitizer: failed to intercept '__isoc99_printf'
==17280==AddressSanitizer: failed to intercept '__isoc99_sprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_snprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_fprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_vprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_vsprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_vsnprintf'
==17280==AddressSanitizer: failed to intercept '__isoc99_vfprintf'
==17280==AddressSanitizer: failed to intercept '__cxa_throw'
==17280==AddressSanitizer: libc interceptors initialized
|| `[0x10007fff8000, 0x7fffffffffff]` || HighMem    ||
|| `[0x02008fff7000, 0x10007fff7fff]` || HighShadow ||
|| `[0x00008fff7000, 0x02008fff6fff]` || ShadowGap  ||
|| `[0x00007fff8000, 0x00008fff6fff]` || LowShadow  ||
|| `[0x000000000000, 0x00007fff7fff]` || LowMem     ||
MemToShadow(shadow): 0x00008fff7000 0x000091ff6dff 0x004091ff6e00 0x02008fff6fff
redzone=16
max_redzone=2048
quarantine_size_mb=256M
thread_local_quarantine_size_kb=1024K
malloc_context_size=30
SHADOW_SCALE: 3
SHADOW_GRANULARITY: 8
SHADOW_OFFSET: 0x7fff8000
==17280==Installed the sigaction for signal 11
==17280==Installed the sigaction for signal 7
==17280==Installed the sigaction for signal 8
==17280==T0: stack [0x7ffd5c1aa000,0x7ffd5c9aa000) size 0x800000; local=0x7ffd5c9a7fe0
==17280==LeakSanitizer: Dynamic linker not found. TLS will not be handled correctly.
==17280==AddressSanitizer Init done
==17280==T1: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T1 TSDDtor
==17280==T1 exited
==17280==T2: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T2 TSDDtor
==17280==T2 exited
==17280==T3: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T3 TSDDtor
==17280==T3 exited
==17280==T4: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T4 TSDDtor
==17280==T4 exited
==17280==T5: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T5 TSDDtor
==17280==T5 exited
==17280==T6: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T6 TSDDtor
==17280==T6 exited
==17280==T7: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T7 TSDDtor
==17280==T7 exited
==17280==T8: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T8 TSDDtor
==17280==T8 exited
==17280==T9: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T9 TSDDtor
==17280==T9 exited
==17280==T10: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T10 TSDDtor
==17280==T10 exited
==17280==T11: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T11 TSDDtor
==17280==T11 exited
==17280==T12: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T12 TSDDtor
==17280==T12 exited
==17280==T13: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T13 TSDDtor
==17280==T13 exited
==17280==T14: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T14 TSDDtor
==17280==T14 exited
==17280==T15: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T15 TSDDtor
==17280==T15 exited
==17280==T16: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T16 TSDDtor
==17280==T16 exited
==17280==T17: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T17 TSDDtor
==17280==T17 exited
==17280==T18: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T18 TSDDtor
==17280==T18 exited
==17280==T19: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T19 TSDDtor
==17280==T19 exited
==17280==T20: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T20 TSDDtor
==17280==T20 exited
==17280==T21: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T21 TSDDtor
==17280==T21 exited
==17280==T22: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T22 TSDDtor
==17280==T22 exited
==17280==T23: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T23 TSDDtor
==17280==T23 exited
==17280==T24: stack [0x7f580cafe000,0x7f580ccfde80) size 0x1ffe80; local=0x7f580ccfdd90
==17280==T24 TSDDtor
==17280==T24 exited
==17377==Could not attach to thread 17280 (errno 1).
==17377==Failed suspending threads.
==17280==LeakSanitizer has encountered a fatal error.
==17280==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
==17280==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)

```
</details>

This is with Ubuntu 16.04 on the latest Rust nightly (`rustc 1.19.0-nightly (d47cf08d5 2017-05-28)`).

### PR DESCRIPTION
**Pull request by alanhdu**
Pass in `--target` in `run-fuzzer.sh` to avoid sanitizing build scripts.

Closes #70.

### CODE REVIEW

File: run-fuzzer.sh [hunk 1]
```diff
@@ -32,4 +32,4 @@ mkdir -p seeds
 mkdir -p corpus
 
 # Run the fuzzer with that target
-cargo run --bin "$2" -- ${@:3} `pwd`/corpus `pwd`/seeds
+cargo run --target x86_64-unknown-linux-gnu --bin "$2" -- ${@:3} `pwd`/corpus `pwd`/seeds
```
Comment (killercup) [inline run-fuzzer.sh]: Any chance of detecting OS X and use x86_64-apple-darwin here?

**Comment by killercup** [comment]
Awesome, thanks for the quick update!

**Comment by alanhdu** [comment]
So I think this works, but I don't have a Mac to test it out on 😞.

**Comment by killercup** [comment]
Just tested it on my macbook, works find. I'll merge when Travis agrees :)

**Comment by killercup** [comment]
@frewsxcv your new bot doesn't like me :(

**Comment by frewsxcv** [comment]
woops, just fixed that! you should have permissions now

bors r=killercup
